"""Utility functions for the obfuscators."""

import random
import string
from pathlib import Path


def generate_random_name() -> str:
    """
    Generate a random string.

    Returns
    -------
    str
        string generated by the function
    """
    random.seed()
    lenght = random.randint(5, 20)
    char_set = string.ascii_letters + string.digits
    return "".join([random.choice(string.ascii_letters), *random.choices(
        char_set, k=lenght)])

def read_smali_file(smali_file: str) -> list[str]:
    """
    Read the content of a smali file.

    Parameters
    ----------
    smali_file : str
        The path to the smali file.

    Returns
    -------
    list[str]
        The content of the smali file.
    """
    with Path(smali_file).open(encoding="utf-8") as current_file:
        return current_file.readlines()

def write_smali_file(smali_file: str, lines: list[str]) -> None:
    """
    Write the content of a smali file.

    Parameters
    ----------
    smali_file : str
        The path to the smali file.
    lines : list[str]
        The content to write in the smali file.
    """
    with Path(smali_file).open("w", encoding="utf-8") as current_file:
        current_file.writelines(lines)
